### ISSUE TITLE
It would be cool if we could open a fixed-width file using an ffs style config

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#585] opened 2016-03-23 22:59 UTC
Maybe something like this

```python
Table.from_csv(fixed_path, fixed_width_format="./myconfig.csv")
```

Though that kwarg is kind of weird. Maybe something like this would be better?

```python
Table.from_fixed_width(fixed_path, format="./myconfig.csv")
```

Or maybe something totally different. But something that solved this would be great.

**Comment by nbedi** [comment] 2016-03-23 23:07
Dupe of #358?

**Comment by onyxfish** [comment] 2016-03-29 23:50
Yep, dupe. On the TODO list.

**Closed by onyxfish** 2016-03-29 23:50 UTC
