### ISSUE TITLE
Should row names be tested for uniqueness?

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#614] opened 2016-05-26 19:28 UTC
Currently possible to create silent errors where a row key is duplicated

However, this could add a ton of table creation overhead

**Comment by jpmckinney** [comment] 2021-07-14 16:42
The API is "Specifies unique names for each row". Obviously, it'd be nice to warn the user if their row names aren't unique, but this is a nice-to-have feature – not a bug. As there is no demand for the feature, I am closing.

**Closed by jpmckinney** 2021-07-14 16:42 UTC
Labels: bug, priority-normal
