### ISSUE TITLE
PyICU dependency causing pip upgrade failure on macOS

### ISSUE THREAD

**Issue by anthonydb** [wireservice/agate#755] opened 2021-03-15 13:20 UTC
Attempting to update to the latest version of agate causes an error on macOS:

`FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'`

I may be wrong, but after a bunch of reading, it looks like the culprit is the PyICU dependency, which, according to that library's author, cannot be pip installed:

https://github.com/ovalhub/pyicu/issues/141#issuecomment-797807893

**Comment by tommyjcarpenter** [comment] 2021-03-15 20:00
this is a dupe of the issue I raised last week here: https://github.com/wireservice/agate/issues/754

**Comment by anthonydb** [comment] 2021-03-15 22:10
Generates a different error on macOS even though it has the same issue at its root.

**Comment by palewire** [comment] 2021-05-31 17:59
This also causes install errors far far far downstream on Heroku, where the PyICU library can't compile.

https://stackoverflow.com/questions/31975668/installation-of-pyicu-on-heroku

**Comment by palewire** [comment] 2021-06-05 05:50
My hopes are not high for heroku after reading this https://gitlab.pyicu.org/main/pyicu/-/issues/150

**Comment by jpmckinney** [comment] 2021-07-12 22:25
I've made a commit that removes the PyICU dependency. Let me know if it works, and I'll make a release.

**Closed by jpmckinney** 2021-07-12 22:25 UTC

**Comment by palewire** [comment] 2021-07-13 18:45
I trust you on it. I say let it rip.

**Comment by tommyjcarpenter** [comment] 2021-07-14 10:32
is there a PR to review?

**Comment by anthonydb** [comment] 2021-07-14 12:37
I'm still getting this error on macOS with version 1.6.2. Do you need to also specify `darwin` for `sys_platform` in `setup.py`?

**Comment by jpmckinney** [comment] 2021-07-14 16:18
It will be fixed in 1.6.3 only.
