### ISSUE TITLE
Clarify vlookup by join documentation

### ISSUE THREAD

**Issue by lindzcook** [wireservice/agate#628] opened 2016-07-06 21:06 UTC
The documentation under "[vlookup](http://agate.readthedocs.io/en/1.4.0/cookbook/excel.html#vlookup)" says that join will add the columns from the passed table to the table on which join is operating. From this description, I expect the number of rows of the resulting table to be the same as the table on which join is operating. Changing the position of the tables doesn't result in differences in the end table row length for me (meaning that I end up with many duplicate rows).

![screen shot 2016-07-06 at 5 01 46 pm](https://cloud.githubusercontent.com/assets/3254939/16634462/d35d9004-439b-11e6-93d7-a585b7aa0e51.png)

**Comment by nbedi** [comment] 2016-07-30 06:03
Hey @lindzcook, sorry for the delay! This is the intended behavior but it is not clear in this vlookup documentation. Join by default will insert new rows for values that exist in the second table but not the first (so order does not matter). You can actually get what you are expecting by setting the `require_match` argument as `True` in the join method:

`test1 = under65_2015_pivot.join(frontmatter, 'FIPS', require_match=True)`

I believe this vlookup documentation was written before `require_match` was implemented. Let me know if that does or does not solve your issue.

**Comment by nbedi** [comment] 2016-08-30 01:01
Sorry @lindzcook, just realized my first response was way off. Could you share the data that caused this (or a subset of the data that still shows this behavior) when you have a chance? There are one or two edge cases that would act like this.

**Comment by lindzcook** [comment] 2016-08-30 15:43
Hey! This project has been published and what exactly was happening and with which data is a little fuzzy to me now. I'll follow up if I see it again. Sorry!

**Comment by nbedi** [comment] 2016-08-30 15:46
No worries, closing for now, let us know if you see it again.

**Closed by nbedi** 2016-08-30 15:46 UTC
Labels: documentation
